using Newtonsoft.Json;

namespace CounosPayClient.Api.V1.Models
{
    public class BaseResponse
    {
        ///// <summary>
        ///// The time that the response generated by server
        ///// </summary>
        [JsonProperty(PropertyName = "currentTime", NullValueHandling = NullValueHandling.Ignore)]
        public int CurrentTime { get; set; }

        ///// <summary>
        ///// Status of the proccessed request
        ///// </summary>
        [JsonProperty(PropertyName = "success", NullValueHandling = NullValueHandling.Ignore)]
        public bool Success { get; set; }

        ///// <summary>
        ///// ‌Body of main response
        ///// </summary>
        [JsonProperty(PropertyName = "data", NullValueHandling = NullValueHandling.Ignore)]
        public object Data { get; set; }

	    [JsonProperty(PropertyName = "message", NullValueHandling = NullValueHandling.Ignore)]
		public string Message { get; set; }

	    [JsonProperty(PropertyName = "devError", NullValueHandling = NullValueHandling.Ignore)]
	    public string DevError { get; set; }

	    [JsonProperty(PropertyName = "errors", NullValueHandling = NullValueHandling.Ignore)]
	    public string Errors { get; set; }
    }
}
